### ISSUE TITLE
How to get the result of Coreference Resolution?

### ISSUE THREAD

**Issue by Takeru0618** [seq-to-mind/coref_dial_summ#1]
I've run dialogue_coreference.py and end2end_build_data.py.
However I get the result like this:
_# ĠHannah : ĠHey , Ġdo Ġyou Ġhave ĠBetty 's Ġnumber ? Ġ# ĠAmanda : ĠLem me Ġcheck Ġ# ĠHannah : Ġ< file _ gif > Ġ# ĠAmanda : ĠSorry , Ġcan 't Ġfind Ġit . Ġ# ĠAmanda : ĠAsk ĠLarry Ġ# ĠAmanda : ĠHe Ġcalled Ġher Ġlast Ġtime Ġwe Ġwere Ġat Ġthe Ġpark Ġtogether Ġ# ĠHannah : ĠI Ġdon 't Ġknow Ġhim Ġwell Ġ# ĠHannah : Ġ< file _ gif > Ġ# ĠAmanda : ĠDon 't Ġbe Ġshy , Ġhe 's Ġvery Ġnice Ġ# ĠHannah : ĠIf Ġyou Ġsay Ġso .. Ġ# ĠHannah : ĠI 'd Ġrather Ġyou Ġtexted Ġhim Ġ# ĠAmanda : ĠJust Ġtext Ġhim Ġ# ĠHannah : ĠUr gh .. ĠAlright Ġ# ĠHannah : ĠBye Ġ# ĠAmanda : ĠBye Ġbye ##### [10431, 11029, 35, 11468, 6, 109, 47, 33, 16666, 18, 346, 116, 849, 10641, 35, 13956, 1794, 1649, 849, 11029, 35, 28696, 21710, 1215, 47324, 15698, 849, 10641, 35, 19719, 6, 64, 75, 465, 24, 4, 849, 10641, 35, 12738, 6045, 849, 10641, 35, 91, 373, 69, 94, 86, 52, 58, 23, 5, 2221, 561, 849, 11029, 35, 38, 218, 75, 216, 123, 157, 849, 11029, 35, 28696, 21710, 1215, 47324, 15698, 849, 10641, 35, 1599, 75, 28, 9152, 6, 37, 18, 182, 2579, 849, 11029, 35, 318, 47, 224, 98, 7586, 849, 11029, 35, 38, 1017, 1195, 47, 25199, 123, 849, 10641, 35, 1801, 2788, 123, 849, 11029, 35, 9163, 4147, 7586, 41881, 849, 11029, 35, 36255, 849, 10641, 35, 36255, 15687] ##### [13, 19, 27, 34, 37, 42, 46, 56, 58, 62, 65, 73, 80, 85, 88, 93, 95, 98, 100, 102, 106, 108, 115, 119] ##### [6, 1, 13, 10, 27, 37, 8, 19, 56, 44, 58, 42, 62, 65, 73, 85, 93, 88, 80, 98, 100, 95, 108, 102] ##### 123

where is the result of Coreference Resolution?

**Comment by seq-to-mind** [comment]
@Takeru0618 

Here is the content mapping of each processed line (as the example you show):
Text Tokens after BART tokenization ##### Token IDs after BART tokenization ##### Start Token ID of One Coreference-Linked Span ##### Target Token ID of One Coreference-Linked Span ##### Token Number after BART tokenization

To obtain the data:
1. Split the line with delimiter "#####".
2. Convert the `Token IDs after BART tokenization` to list of integer type values.
3. Convert the `Start Token ID of One Coreference-Linked Span` and `Target Token ID of One Coreference-Linked Span` to integer lists.
4. Each paired value in the two lists extracted from Step [3] is one coreference link (from start span to target span).
5. You can use the `Token Number after BART tokenization` to check the tokenized sequence length.
